### ISSUE TITLE
Incorporate various T-P profile parametrizations in a consistent way

### ISSUE THREAD

**Issue by adadams** [alexrhowe/APOLLO#18]
I think this would be easiest by calculating out the profiles on the Python side, and just feeding the C++ side an array of temperatures. Then you can just plug in whatever functional form you want, where the "free layer-by-layer" profile is technically its own functional form - interpolation from an arbitrary number of arguments - which is also easier to implement on the Python side.

**Comment by alexrhowe** [comment]
Folded into Issue #10
