### ISSUE TITLE
MakePlanet() must be called before each call to GetModel(), to get consistent results when multiple bands are present

### ISSUE THREAD

**Issue by adadams** [alexrhowe/APOLLO#66]

**Comment by alexrhowe** [comment]
@adadams Can you elaborate on this? This doesn't make sense with respect to how the code works, and there is no way that would run efficiently.

**Comment by adadams** [comment]
I meant this as descriptive rather than prescriptive, bad wording there. I can look into this; I remember it being for a specific set of models I was running, and I may have resolved it by resolving another issue. I will check this and get back to you!

**Comment by alexrhowe** [comment]
Moot after changes made to band handling.
